name:  Bug Report
description: Report a bug or issue with the Lootjes Trekker application
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees:
  - BlubDevllc

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out this form completely to help us understand and fix the issue.

  - type: checkboxes
    id: license-acknowledgment
    attributes:
      label: License Acknowledgment
      description: Please confirm you understand the project license restrictions
      options:
        - label: I have read and understand the [SCVL license terms](../docs/LICENSE_UITLEG.md)
          required: true
        - label: This bug report is for educational/learning purposes only
          required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Tell us how to reproduce this bug
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Enter '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what you expected...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: dropdown
    id: bug-type
    attributes:
      label: Bug Type
      description: What type of bug is this?
      options:
        - Lottery Algorithm Issue
        - User Interface (UI) Problem
        - User Experience (UX) Issue
        - Performance Problem
        - Browser Compatibility
        - Accessibility Issue
        - JavaScript Error
        - CSS Styling Problem
        - Mobile/Responsive Issue
        - Documentation Error
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (Application completely broken)
        - High (Major functionality affected)
        - Medium (Some functionality affected)
        - Low (Minor issue or cosmetic)
    validations:
      required: true

  - type: textarea
    id: browser-info
    attributes:
      label: Browser Information
      description: |
        Please provide browser and system information
      placeholder: |
        - Browser: Chrome 121.0.0.0
        - Operating System: Windows 11
        - Screen Resolution: 1920x1080
        - Mobile Device: iPhone 15 Pro (if applicable)
    validations:
      required: true

  - type: textarea
    id: console-errors
    attributes:
      label: Console Errors
      description: |
        Please paste any JavaScript console errors (Press F12 → Console)
      placeholder: |
        Paste console errors here...
      render: text

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: |
        If applicable, add screenshots to help explain your problem
        You can drag and drop images here
      placeholder: Drag and drop screenshots here...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: |
        Add any other context about the problem here
        - Does this happen consistently?
        - Are there any workarounds?
        - When did this start happening?
      placeholder: Any additional information...

  - type: dropdown
    id: affected-features
    attributes:
      label: Affected Features
      description: Which features are affected by this bug?
      multiple: true
      options:
        - Adding participants
        - Removing participants
        - Setting number of tickets
        - Drawing lottery
        - Displaying results
        - Statistics calculation
        - Mobile responsiveness
        - Accessibility features
        - Performance
        - All features

  - type: checkboxes
    id: testing-checklist
    attributes:
      label: Testing Checklist
      description: Please confirm you've tested these scenarios
      options:
        - label: I tested this in a different browser
        - label: I tested this in an incognito/private window
        - label: I cleared browser cache and cookies
        - label: I checked the browser console for errors
        - label: I tried with different input data

  - type: markdown
    attributes:
      value: |
        ## Thank You!
        
        Your bug report helps improve the Lootjes Trekker for everyone learning from this project. 
        
        **Next Steps:**
        1. We'll review your report within 48 hours
        2. We may ask for additional information
        3. We'll work on a fix and keep you updated
        
        **Educational Value:**
        This bug report also serves as a learning example for:
        - How to write effective bug reports
        - Understanding application testing
        - Contributing to open source projects
